// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package widgets

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func VacancyCard() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = VacancyCardStyle().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"VacancyCard\"><div class=\"VacancyCard__left\"><div class=\"VacancyCard__left-time\">10 минут назад </div><div class=\"VacancyCard__left-hero\"><div class=\"VacancyCard__left-hero-logo\">logo</div><div class=\"VacancyCard__left-hero-text\"><div class=\"VacancyCard__left-hero-header\">Директор по продажам</div><div class=\"VacancyCard__left-hero-headling\">ООО Василий</div></div></div><div class=\"VacancyCard__left-info\"><div class=\"VacancyCard__left-info-block\"><div class=\"VacancyCard__left-info-type-logo\">logo</div><div class=\"VacancyCard__left-info-block-text\">Медиа</div></div><div class=\"VacancyCard__left-info-block\"><div class=\"VacancyCard__left-info-salary-logo\">logo</div><div class=\"VacancyCard__left-info-block-text\">300 000 руб</div></div><div class=\"VacancyCard__left-info-block\"><div class=\"VacancyCard__left-info-location-logo\">logo</div><div class=\"VacancyCard__left-info-block-text\">Москва</div></div></div></div><div class=\"VacancyCard__right\"></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func VacancyCardStyle() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<style>\n        .VacancyCard{\n            display: flex;\n            flex-direction: row;\n            justify-content: space-between;\n            padding: 40px;\n            border-radius: 20px;\n            box-shadow: 0 3px 8px 0 rgba(48, 150, 137, 0.08);\n            background: #fff;\n            margin: 0 72px 24px 72px ;\n        } \n        .VacancyCard__left{\n            display: flex;\n            flex-direction: column;\n        }\n        .VacancyCard__left-time{\n            background: rgba(48, 150, 137, 0.1);\n            border-radius: 8px;\n            padding: 8px;\n            width: 136px;\n            height: 28px;\n            font-size: 16px;\n            color: #309689;\n        }\n        .VacancyCard__left-hero{\n            display: flex;\n            flex-direction: row;\n            gap: 20px;\n        }\n        .VacancyCard__left-hero-text{\n            display: flex;\n            flex-direction: column;\n            gap: 20px;\n        }\n        .VacancyCard__left-hero-header{\n          font-weight: 600;\n          font-size: 28px;\n          color: #000;  \n        }\n        .VacancyCard__left-hero-headling{\n          font-weight: 400;\n          font-size: 16px;\n          color: #000;\n        }\n        .VacancyCard__left-info{\n            display: flex;\n            flex-direction: row;\n            gap: 24px;\n        }\n        .VacancyCard__left-info-block{\n            display: flex;\n            gap: 12px;\n        }\n        .VacancyCard__left-info-block{\n            font-weight: 600;\n            font-size: 16px;\n            color: #6c757d;\n        }\n    </style>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
